pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: assign PRs with JS files modified to Rehman
    conditions:
      - files~=\.js$
      - -closed
    actions:
      assign:
        add_users:
          - MD-REHMAN
  - name: assign PRs with markdown files modified to team
    conditions:
      - files~=\.md$
      - -closed
    actions:
      assign:
        add_users:
          - MirzaFaizanBaig
          - Rehan025
  - name: assign PRs with yml files modified to team
    conditions:
      - files~=\.yml$
      - -closed
    actions:
      assign:
        add_users:
          - MirzaFaizanBaig
          - Rehan025